### ISSUE TITLE
Plugin regressed/template env field not showing

### ISSUE THREAD

**Issue by jaepass** [jlengstorf/netlify-plugin-onboarding#1]
Hi Jason, we have an OS project and have been working with Phil with pushing out a blog article on it. Because this project requires env vars for a successful deployment, Phil suggested your plugin which worked beautifully with seamless onboarding. Somehow now the plugin has regressed and I'm wondering if you might know what the issue might be.
I've included the `template.environment` [here](https://github.com/chec/commercejs-nextjs-demo-store/blob/master/netlify.toml), had tested a few deployments and worked just fine previously.

![Screen Shot 2020-06-23 at 4 42 22 PM](https://user-images.githubusercontent.com/48780927/86488642-8a925f00-bd16-11ea-92b0-f77d9e092500.png)

I will continue to investigate!

**Comment by jlengstorf** [comment]
thanks so much for bringing this to my attention! we’ll review this first thing next week and I’ll report back — looks like an accidental regression

**Comment by jaepass** [comment]
Thank you Jason, appreciate it!

**Comment by jlengstorf** [comment]
this was a regression in our UI. a patch is in place and will be published soon

**Comment by jaepass** [comment]
Awesome thanks for digging into this!

**Comment by jlengstorf** [comment]
@jaepass this should be patched now — can you give it a shot and make sure it's working the way you expect?

thanks!

**Comment by jaepass** [comment]
Boom, thanks a ton Jason its working as expected!

**Comment by jlengstorf** [comment]
great news!
